version: '3.8'
services:
  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/google-docs-clone
    depends_on:
      - mongo

  react-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    depends_on:
      - node-server

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6:
